### ISSUE TITLE
[Feature Request] Support IBM Mini-M new RPi controller

### ISSUE THREAD

**Issue by apastuszak** [purdeaandrei/vial-qmk-overnumpad-and-aristides-2862#1]
## Feature Request Type

- [x] Core functionality
- [ ] Add-on hardware support (eg. audio, RGB, OLED screen, etc.)
- [ ] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

I would love it if we could get support for the Unicomp Mini-M with the new Raspberry Pi Mini-M based controller.

**Comment by purdeaandrei** [comment]
Hey, just received my Mini M,
I will try to find some time in the weekend to write firmware for it.

**Comment by apastuszak** [comment]
Thank you!

I got a Pico-based controller in the mail last week to put into my keyboard. I'll be happy to test.

**Comment by purdeaandrei** [comment]
@apastuszak  You will find firmware to the new pico-based controlled (called Justify + Mike Smith), over here: https://github.com/purdeaandrei/vial-qmk-mini-m/releases/latest
